/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-12-08 07:34:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import dto.lecture;
import dao.lectures;
import java.util.*;

public final class lectureManager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/HeaderAdminLogin.jsp", Long.valueOf(1733505794197L));
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1733141697245L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("dto.lecture");
    _jspx_imports_classes.add("dao.lectures");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("margin-top: 180px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#InputTable {\n");
      out.write("width : 90%;\n");
      out.write("margin-left : auto;\n");
      out.write("margin-right : auto;\n");
      out.write("font-size : 17px;\n");
      out.write("border-collapse : collapse;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#InputTrId1 {\n");
      out.write("text-align : center;\n");
      out.write("height : 35px;\n");
      out.write("border-bottom : 1px solid black;\n");
      out.write("border-top : 1px solid black;\n");
      out.write("background-color : #F9F5F9 ;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#listHr{\n");
      out.write("border : 0px;\n");
      out.write("height : 2px;\n");
      out.write("background : black;\n");
      out.write("width : 20px;\n");
      out.write("margin-left : 5%;\n");
      out.write("margin-top: 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#listTitle {\n");
      out.write("font-size : 25x;\n");
      out.write("margin-left : 5%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#InputHr{\n");
      out.write("border : 0px;\n");
      out.write("height : 2px;\n");
      out.write("background : black;\n");
      out.write("width : 20px;\n");
      out.write("margin-left : 5%;\n");
      out.write("margin-top: 180px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#InputHr2{\n");
      out.write("border : 0px;\n");
      out.write("height : 2px;\n");
      out.write("background : black;\n");
      out.write("width : 20px;\n");
      out.write("margin-left : 5%;\n");
      out.write("margin-top: 180px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#InputTrId2 {\n");
      out.write("text-align : center;\n");
      out.write("height : 40px;\n");
      out.write("border-bottom : 1px solid #C2C5CC ;\n");
      out.write("margin-left: auto;\n");
      out.write("margin-right : auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#send {\n");
      out.write("background-color : black;\n");
      out.write("border-radius :5px;\n");
      out.write("color : white;\n");
      out.write("height : 28px;\n");
      out.write("width: 38px;\n");
      out.write("border : none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#t1,#t2,#t3,#t4,#t5,#t6,#t7,#t8,#t9,#t10,#t11,#t12,#t13,#t14,#t15,#t16,#t17,#t18 {\n");
      out.write("width : 55px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#listTable { \n");
      out.write("width : 90%;\n");
      out.write("margin-left : auto;\n");
      out.write("margin-right : auto;\n");
      out.write("border-collapse : collapse;\n");
      out.write("text-align : center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#listTr {\n");
      out.write("height : 35px;\n");
      out.write("background-color:black;\n");
      out.write("color : white;\n");
      out.write("font-size : 17px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#listLecTr { \n");
      out.write("border-bottom: 1px solid #C2C5CC;\n");
      out.write("height : 40px;\n");
      out.write("font-size : 16px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#InputTitle {\n");
      out.write("font-size : 25px;\n");
      out.write("margin-left : 5%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#edit {\n");
      out.write("background-color : black;\n");
      out.write("border-radius :5px;\n");
      out.write("border : none;\n");
      out.write("height : 25px;\n");
      out.write("color : white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#delete {\n");
      out.write("background-color : #333435;\n");
      out.write("border : none;\n");
      out.write("height : 25px;\n");
      out.write("border-radius :5px;\n");
      out.write("color : white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#listTitle { \n");
      out.write("margin-left : 5%;\n");
      out.write("font-size : 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#planTitle { \n");
      out.write("text-align : center;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/Header.css\" rel = \"stylesheet\">\r\n");
      out.write("<title>한성대학교 수강신청 페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<nav class = \"navbar navbar-default\">\r\n");
      out.write("		<a class=\"Logo\" href=\"LoginAdmin.jsp\"><img src=\"img/logo.png\" alt=\"한성대 로고\"></a>\r\n");
      out.write("		<div class=\"nav\">\r\n");
      out.write("		<ul class=\"nav-bar\">\r\n");
      out.write("			<li><a href=\"Admin.jsp\">로그아웃</a></li>\r\n");
      out.write("			<li><a href=\"Notice.jsp\">공지사항</a></li>\r\n");
      out.write("			<li><a href=\"lectureManager.jsp\">관리자용</a></li>\r\n");
      out.write("			<li><a href=\"Infor.jsp\">수강신청 안내</a></li>\r\n");
      out.write("			<li><a href=\"lecturesPlan.jsp\">강의계획서 조회</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("<title>관리자용 페이지(2171030 남유진)</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");

lectures dao = lectures.getInstance();
ArrayList<lecture> lecturess = dao.getAllLectures();

      out.write("   \n");
      out.write("<hr id = \"InputHr\">\n");
      out.write("<p id = \"InputTitle\">과목 추가 및 변경창</p>\n");
      out.write("<form action = \"lectureMethod.jsp\" method=\"get\">\n");
      out.write("<table id = \"InputTable\"> \n");
      out.write("<tr id = \"InputTrId1\"> \n");
      out.write("<td> \n");
      out.write("<td> 트랙 \n");
      out.write("<td> 코드  \n");
      out.write("<td> 학점 \n");
      out.write("<td> 학년 \n");
      out.write("<td> 이름 \n");
      out.write("<td> 분류 \n");
      out.write("<td> 분반 \n");
      out.write("<td> 교수 \n");
      out.write("<td> 교실 \n");
      out.write("<td> 수업1\n");
      out.write("<td> 시작1 \n");
      out.write("<td> 종료1 \n");
      out.write("<td> 수업2 \n");
      out.write("<td> 시작2 \n");
      out.write("<td> 종료2 \n");
      out.write("<td> 정보 \n");
      out.write("<td> 인원 \n");
      out.write("<td> \n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("<tr id = \"InputTrId2\"> \n");
      out.write("<td> <input name = \"EAD\" id = \"EAD\" type = \"hidden\"> </td>\n");
      out.write("<td> <input style = \"width: 50px\" name = \"t1\" id = \"t1\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 50px\" name = \"t2\" id = \"t2\" type = \"text\">  </td>\n");
      out.write("<td> <input style = \"width: 12px\" name = \"t3\" id = \"t3\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 12px\" name = \"t4\" id = \"t4\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 50px\" name = \"t5\" id = \"t5\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 25px\"  name = \"t6\" id = \"t6\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 12px\" name = \"t7\" id = \"t7\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 40px\" name = \"t8\" id = \"t8\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 40px\" name = \"t9\" id = \"t9\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 40px\" name = \"t10\" id = \"t10\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 40px\" name = \"t11\" id = \"t11\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 40px\" name = \"t12\" id = \"t12\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 40px\" name = \"t13\" id = \"t13\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 40px\" name = \"t14\" id = \"t14\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 40px\" name = \"t15\" id = \"t15\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 50px\" name = \"t17\" id = \"t17\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"width: 12px\" name = \"t18\" id = \"t18\" type = \"text\"> </td>\n");
      out.write("<td> <input style = \"text-align : left;\" id = \"send\" name = \"click\" type = \"submit\" value = \"변경\" > &nbsp;</input> </td>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<hr id = \"listHr\"> \n");
      out.write("<p id = \"listTitle\">과목 목록</p>\n");
      out.write("\n");
      out.write("<form> \n");
      out.write("<table id = \"listTable\"> \n");
      out.write("<tr id = \"listTr\"> \n");
      out.write("<td> 트랙 \n");
      out.write("<td> 코드  \n");
      out.write("<td> 학점 \n");
      out.write("<td> 학년 \n");
      out.write("<td> 이름 \n");
      out.write("<td> 분류 \n");
      out.write("<td> 분반 \n");
      out.write("<td> 교수 \n");
      out.write("<td> 교실 \n");
      out.write("<td> 수업1 \n");
      out.write("<td> 시작1 \n");
      out.write("<td> 종료1 \n");
      out.write("<td> 수업2 \n");
      out.write("<td> 시작2 \n");
      out.write("<td> 종료2 \n");
      out.write("<td> 정보 \n");
      out.write("<td> 인원 \n");
      out.write("<td> 기능 \n");
      out.write("</tr>\n");
      out.write("<div id = \"chooseTable\">\n");
 
for (int i = 0; i < lecturess.size(); i++) {
lecture lecture = lecturess.get(i);

      out.write("\n");
      out.write("</div> \n");
      out.write("\n");
      out.write("<tr name = \"listLecTr\" id = \"listLecTr\"> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureTrack() );
      out.write(" </td> </div>\n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureCode() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureCredit() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureGrade() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureName() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureSort() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureDivision() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureProf() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureClassRoom() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureDay1() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureStart1() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureEnd1() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureDay2() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureStart2() );
      out.write(" </td> </div> \n");
      out.write("<div> <td> ");
      out.print(lecture.getLectureEnd2() );
      out.write(" </td> </div> \n");
      out.write("<td> <div style = \"font-size:10px; overflow:hidden;white-space:nowrap;text-overflow:ellipsis;width:30px;\"> ");
      out.print(lecture.getLectureInformation() );
      out.write(" </div> </td>\n");
      out.write("<div> <td> ");
      out.print(lecture.getLecturePeople() );
      out.write(" </td>  \n");
      out.write("<div> <td> <input id = \"edit\" type = \"button\" value = \"수정\" \n");
      out.write("onclick =\"document.getElementById('t1').value = '");
      out.print(lecture.getLectureTrack());
      out.write("';\n");
      out.write("document.getElementById('t2').value = '");
      out.print(lecture.getLectureCode());
      out.write("';\n");
      out.write("document.getElementById('t3').value = '");
      out.print(lecture.getLectureCredit());
      out.write("'; \n");
      out.write("document.getElementById('t4').value = '");
      out.print(lecture.getLectureGrade() );
      out.write("';\n");
      out.write("document.getElementById('t5').value = '");
      out.print(lecture.getLectureName() );
      out.write("';  \n");
      out.write("document.getElementById('t6').value = '");
      out.print(lecture.getLectureSort() );
      out.write("';\n");
      out.write("document.getElementById('t7').value = '");
      out.print(lecture.getLectureDivision());
      out.write("';\n");
      out.write("document.getElementById('t8').value = '");
      out.print(lecture.getLectureProf() );
      out.write("';\n");
      out.write("document.getElementById('t9').value = '");
      out.print(lecture.getLectureClassRoom() );
      out.write("';\n");
      out.write("document.getElementById('t10').value = '");
      out.print(lecture.getLectureDay1() );
      out.write("';\n");
      out.write("document.getElementById('t11').value = '");
      out.print(lecture.getLectureStart1() );
      out.write("';\n");
      out.write("document.getElementById('t12').value = '");
      out.print(lecture.getLectureEnd1() );
      out.write("';\n");
      out.write("document.getElementById('t13').value = '");
      out.print(lecture.getLectureDay2() );
      out.write("';\n");
      out.write("document.getElementById('t14').value = '");
      out.print(lecture.getLectureStart2() );
      out.write("';\n");
      out.write("document.getElementById('t15').value = '");
      out.print(lecture.getLectureEnd2() );
      out.write("';\n");
      out.write("document.getElementById('t17').value = '");
      out.print(lecture.getLectureInformation() );
      out.write("';\n");
      out.write("document.getElementById('t18').value = '");
      out.print(lecture.getLecturePeople());
      out.write("';\n");
      out.write("document.getElementById('EAD').value = '");
      out.print(i);
      out.write("';\n");
      out.write("\"> </input> \n");
      out.write("<input id = \"delete\" type = \"button\" value = \"삭제\" \n");
      out.write("onclick = \"document.getElementById('t1').value = '");
      out.print(lecture.getLectureTrack());
      out.write("';\n");
      out.write("document.getElementById('t2').value = '");
      out.print(lecture.getLectureCode());
      out.write("';\n");
      out.write("document.getElementById('t3').value = '");
      out.print(lecture.getLectureCredit());
      out.write("'; \n");
      out.write("document.getElementById('t4').value = '");
      out.print(lecture.getLectureGrade() );
      out.write("';\n");
      out.write("document.getElementById('t5').value = '");
      out.print(lecture.getLectureName() );
      out.write("';  \n");
      out.write("document.getElementById('t6').value = '");
      out.print(lecture.getLectureSort() );
      out.write("';\n");
      out.write("document.getElementById('t7').value = '");
      out.print(lecture.getLectureDivision());
      out.write("';\n");
      out.write("document.getElementById('t8').value = '");
      out.print(lecture.getLectureProf() );
      out.write("';\n");
      out.write("document.getElementById('t9').value = '");
      out.print(lecture.getLectureClassRoom() );
      out.write("';\n");
      out.write("document.getElementById('t10').value = '");
      out.print(lecture.getLectureDay1() );
      out.write("';\n");
      out.write("document.getElementById('t11').value = '");
      out.print(lecture.getLectureStart1() );
      out.write("';\n");
      out.write("document.getElementById('t12').value = '");
      out.print(lecture.getLectureEnd1() );
      out.write("';\n");
      out.write("document.getElementById('t13').value = '");
      out.print(lecture.getLectureDay2() );
      out.write("';\n");
      out.write("document.getElementById('t14').value = '");
      out.print(lecture.getLectureStart2() );
      out.write("';\n");
      out.write("document.getElementById('t15').value = '");
      out.print(lecture.getLectureEnd2() );
      out.write("';\n");
      out.write("document.getElementById('t17').value = '");
      out.print(lecture.getLectureInformation() );
      out.write("';\n");
      out.write("document.getElementById('t18').value = '");
      out.print(lecture.getLecturePeople());
      out.write("';\n");
      out.write("document.getElementById('EAD').value = '100");
      out.print(i);
      out.write("'\n");
      out.write("\"> </input> </td>\n");
      out.write("</tr>\n");
 
}

      out.write("\n");
      out.write("</div>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("</body>\n");
      out.write("<footer>\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link href=\"css/Footer.css\" rel = \"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<footer>\n");
      out.write("<div class=\"text\">\n");
      out.write("	<ul class=\"fText\">\n");
      out.write("	<li><p class=\"left\">개인정보처리방침</p></li>\n");
      out.write("	<li><p class=\"infor\">주소: [02876] 서울특별시 성북구 삼선교로 16길 116(삼선동2가)  Tel : 02-760-4114<br>\n");
      out.write("		Copyright 2024. HANSUNG UNIVERSITY All Rights Reserved.</p></li>\n");
      out.write("	</ul>\n");
      out.write("</div>\n");
      out.write("<div class=\"fLogo\"><p><img src=\"img/logo.png\" alt=\"한성대 로고\"></p></div>\n");
      out.write("</footer>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</footer>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
